### ISSUE TITLE
1.1.2.c.(a,b) "immediately"

### ISSUE THREAD

**Issue by TRManderson** [lsenjov/politico#3]
I assume this literally means that the moment something has a majority of votes in favour, it is merged - rather than 'if it has majority votes on Sunday at 5PM'?

**Comment by lsenjov** [comment]
Majority of votes from all players. If there's 10 players, it requires 6 players to have voted affirmative/negative for it to be ratified/closed.

**Comment by TRManderson** [comment]
What I meant is, is the policy ratified the moment it hits a majority? Or is it ratified the moment it hits Sunday 5PM if there is a majority

**Comment by lsenjov** [comment]
Moment it hits a majority (or when I see it's hit a majority, anyway)
